version: "3.8"
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    # command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: gokapture
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    restart: always
    image: nodeapp:v1
    volumes:
      - ./nodeapp:/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      DB_NAME: gokapture
      DB_CONNECTION_LIMIT: 20
      JWT_SECRET_KEY: f48abbef48ce98ecf6a38bdc07e94275
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 3000
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
